// <auto-generated />
using System;
using AlexDirectorConsole.V2.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlexDirectorConsole.V2.Database.Data.Migrations
{
    [DbContext(typeof(V2DbContext))]
    [Migration("20260904092336_AddProjectType")]
    partial class AddProjectType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AgentDefinitions", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentSkill", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("AgentSkills", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStep")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgressTotal")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByMessageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ProjectId", "Status", "CreatedAtUtc");

                    b.ToTable("AgentTasks", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentTasks_ProgressCompleted", "ProgressCompleted >= 0");

                            t.HasCheckConstraint("CK_AgentTasks_ProgressTotal", "ProgressTotal IS NULL OR ProgressTotal >= 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TaskId", "Sequence")
                        .IsUnique();

                    b.ToTable("AgentTaskEvents", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ObjectResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskId", "Ordinal")
                        .IsUnique();

                    b.HasIndex("TaskId", "Status");

                    b.ToTable("AgentTaskItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentTaskItems_Attempt", "Attempt >= 0");

                            t.HasCheckConstraint("CK_AgentTaskItems_Ordinal", "Ordinal >= 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskOutput", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId", "AssetId", "Role");

                    b.HasIndex("AssetId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("AgentTaskOutputs", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("BlobContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("BlobKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenerationMetadataJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlobKey")
                        .IsUnique();

                    b.HasIndex("CreatedByTaskId");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ProjectId", "Type");

                    b.HasIndex("ProjectId", "Number", "Version")
                        .IsUnique();

                    b.HasIndex("ProjectId", "ResourceId", "Version")
                        .IsUnique();

                    b.ToTable("Assets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Assets_SchemaVersion", "SchemaVersion > 0");

                            t.HasCheckConstraint("CK_Assets_SizeBytes", "SizeBytes >= 0");

                            t.HasCheckConstraint("CK_Assets_Version", "Version > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AssetDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConsumerAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceAssetId");

                    b.HasIndex("ProjectId", "ConsumerAssetId");

                    b.HasIndex("ProjectId", "SourceAssetId");

                    b.HasIndex("ConsumerAssetId", "SourceAssetId", "Role")
                        .IsUnique();

                    b.ToTable("AssetDependencies", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ComfyUiConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageEditWorkflow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextToImageWorkflow")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComfyUiConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ComfyUiConfigurations_MaxConcurrentJobs", "MaxConcurrentJobs > 0");

                            t.HasCheckConstraint("CK_ComfyUiConfigurations_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.CopilotConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("CopilotConversations", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.CopilotMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("CopilotMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_CopilotMessages_Sequence", "Sequence > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BackgroundImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdentityImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutfitImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoiceAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundImageAssetId");

                    b.HasIndex("IdentityImageAssetId");

                    b.HasIndex("OutfitImageAssetId");

                    b.HasIndex("VoiceAssetId");

                    b.HasIndex("ProjectId", "Name");

                    b.ToTable("DigitalPresenters", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenterEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BackgroundImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dialogue")
                        .IsRequired()
                        .HasMaxLength(12000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("OutfitImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresenterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundImageAssetId");

                    b.HasIndex("OutfitImageAssetId");

                    b.HasIndex("PresenterId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("DigitalPresenterEpisodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DigitalPresenterEpisodes_EpisodeNumber", "EpisodeNumber > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenterShot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dialogue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EffectiveCharacterCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FirstFrameAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("VideoAssetId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirstFrameAssetId");

                    b.HasIndex("VideoAssetId");

                    b.HasIndex("EpisodeId", "SortOrder")
                        .IsUnique();

                    b.ToTable("DigitalPresenterShots", null, t =>
                        {
                            t.HasCheckConstraint("CK_DigitalPresenterShots_DurationSeconds", "DurationSeconds BETWEEN 4 AND 15");

                            t.HasCheckConstraint("CK_DigitalPresenterShots_EffectiveCharacterCount", "EffectiveCharacterCount > 0");

                            t.HasCheckConstraint("CK_DigitalPresenterShots_SortOrder", "SortOrder > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DirectorDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionText")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOption")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("RequestedByTaskId");

                    b.HasIndex("SubjectAssetId");

                    b.HasIndex("ProjectId", "Status", "RequestedAtUtc");

                    b.ToTable("DirectorDecisions", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.FoundryConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deployment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageDeployment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageQuality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedApiKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedImageApiKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedVllmApiKey")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("VllmBaseUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VllmModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FoundryConfigurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_FoundryConfigurations_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double?>("TargetSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "EpisodeNumber")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.ToTable("ProductionEpisodes", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductionEpisodes_EpisodeNumber", "EpisodeNumber > 0");

                            t.HasCheckConstraint("CK_ProductionEpisodes_TargetSeconds", "TargetSeconds IS NULL OR TargetSeconds > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreativeSettingsAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FinalAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalInstruction")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreflightValidationRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReferenceBoardAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestedByTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("shot-frames");

                    b.Property<Guid>("ScriptPackageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreativeSettingsAssetId");

                    b.HasIndex("FinalAssetId");

                    b.HasIndex("PreflightValidationRunId");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ReferenceBoardAssetId");

                    b.HasIndex("RequestedByTaskId");

                    b.HasIndex("ScriptPackageAssetId");

                    b.HasIndex("ProjectId", "CreatedAtUtc");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("ProjectId", "ProductionEpisodeId", "CreatedAtUtc");

                    b.HasIndex("RunType", "Status", "CreatedAtUtc");

                    b.ToTable("ProductionRuns", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionRunItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CostJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalJobId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputAssetIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OutputAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotAssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShotName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OutputAssetId");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ShotAssetId");

                    b.HasIndex("RunId", "ShotResourceId", "Stage")
                        .IsUnique();

                    b.ToTable("ProductionRunItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductionRunItems_Attempt", "Attempt >= 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentCreativeSettingsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCreativeSettingsId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ResourceState", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrentAssetId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StaleReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StaleSinceUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId", "ResourceId");

                    b.HasIndex("ApprovedAssetId");

                    b.HasIndex("CurrentAssetId");

                    b.HasIndex("ProjectId", "CurrentAssetId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "ResourceType", "LifecycleStatus");

                    b.ToTable("ResourceStates", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("AgentId", "ScopeKey")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.SessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "Sequence")
                        .IsUnique();

                    b.ToTable("SessionMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_SessionMessages_Sequence", "Sequence > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotAssetLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ProjectId", "ShotResourceId");

                    b.HasIndex("ProjectId", "ShotResourceId", "AssetId", "Role", "SubjectId")
                        .IsUnique();

                    b.ToTable("ShotAssetLinks", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotBeatClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BeatId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdinalInShot")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScriptPackageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScriptPackageAssetId", "BeatId")
                        .IsUnique();

                    b.HasIndex("ShotAssetId", "BeatId")
                        .IsUnique();

                    b.ToTable("ShotBeatClaims", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShotBeatClaims_Ordinal", "OrdinalInShot >= 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScriptPackageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShotAssetId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ShotNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ShotResourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("ScriptPackageAssetId");

                    b.HasIndex("ShotAssetId");

                    b.HasIndex("ProjectId", "ShotResourceId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "ScriptPackageAssetId", "ProductionEpisodeId", "SceneNumber", "ShotNumber")
                        .IsUnique();

                    b.ToTable("ShotDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShotDefinitions_DurationSeconds", "DurationSeconds > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.SkillDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SkillDefinitions", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ValidationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedAction")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ValidationRunId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ValidationRunId", "GateId", "SubjectId")
                        .IsUnique();

                    b.HasIndex("ValidationRunId", "Status", "Severity");

                    b.ToTable("ValidationResults", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ValidationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductionEpisodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TriggeredByTaskId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatorSet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatorVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionEpisodeId");

                    b.HasIndex("SubjectAssetId");

                    b.HasIndex("TriggeredByTaskId");

                    b.HasIndex("ProjectId", "SubjectAssetId", "StartedAtUtc");

                    b.ToTable("ValidationRuns", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VisualReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApprovedByDecisionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImageAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InheritsFromAssetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByDecisionId");

                    b.HasIndex("InheritsFromAssetId");

                    b.HasIndex("ImageAssetId", "SubjectResourceId", "Purpose")
                        .IsUnique();

                    b.HasIndex("ProjectId", "SubjectResourceId", "ReviewStatus");

                    b.ToTable("VisualReferences", (string)null);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VoicePackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanExport")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Dialect")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("GptWeightsPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ReferenceAudioContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ReferenceAudioContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceAudioFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoVitsWeightsPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsagePolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("VoiceTrainingJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VoiceTrainingJobId");

                    b.HasIndex("ResourceId", "Version")
                        .IsUnique();

                    b.HasIndex("IsCurrent", "IsEnabled", "Name");

                    b.ToTable("VoicePackages", null, t =>
                        {
                            t.HasCheckConstraint("CK_VoicePackages_DefaultSpeed", "DefaultSpeed >= 0.5 AND DefaultSpeed <= 2.0");

                            t.HasCheckConstraint("CK_VoicePackages_Version", "Version > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VoiceTrainingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanExport")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultSpeed")
                        .HasColumnType("REAL");

                    b.Property<string>("Dialect")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalJobId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GptWeightsPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RightsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoVitsWeightsPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsagePolicy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "UpdatedAtUtc");

                    b.ToTable("VoiceTrainingJobs", null, t =>
                        {
                            t.HasCheckConstraint("CK_VoiceTrainingJobs_DefaultSpeed", "DefaultSpeed >= 0.5 AND DefaultSpeed <= 2.0");

                            t.HasCheckConstraint("CK_VoiceTrainingJobs_ProgressPercent", "ProgressPercent >= 0 AND ProgressPercent <= 100");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VoiceTrainingSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("AudioContent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VoiceTrainingJobId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VoiceTrainingJobId", "SortOrder")
                        .IsUnique();

                    b.ToTable("VoiceTrainingSamples", null, t =>
                        {
                            t.HasCheckConstraint("CK_VoiceTrainingSamples_DurationSeconds", "DurationSeconds > 0");
                        });
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentSkill", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.SkillDefinition", null)
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTask", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskEvent", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskItem", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AgentTaskOutput", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Asset", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("CreatedByTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.AssetDependency", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ConsumerAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("SourceAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.CopilotConversation", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.CopilotMessage", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.CopilotConversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenter", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("BackgroundImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("IdentityImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("OutfitImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("VoiceAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenterEpisode", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("BackgroundImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("OutfitImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.DigitalPresenter", null)
                        .WithMany()
                        .HasForeignKey("PresenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DigitalPresenterShot", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.DigitalPresenterEpisode", null)
                        .WithMany()
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("FirstFrameAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("VideoAssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.DirectorDecision", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("RequestedByTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("SubjectAssetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionRun", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("CreativeSettingsAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("FinalAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ValidationRun", null)
                        .WithMany()
                        .HasForeignKey("PreflightValidationRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ReferenceBoardAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("RequestedByTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ScriptPackageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ProductionRunItem", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("OutputAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ShotAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Project", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("CurrentCreativeSettingsId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ResourceState", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ApprovedAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("CurrentAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.Session", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentDefinition", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.SessionMessage", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotAssetLink", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotBeatClaim", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ScriptPackageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ShotAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ShotDefinition", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ScriptPackageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ShotAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ValidationResult", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ValidationRun", null)
                        .WithMany()
                        .HasForeignKey("ValidationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.ValidationRun", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.ProductionEpisode", null)
                        .WithMany()
                        .HasForeignKey("ProductionEpisodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("SubjectAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.AgentTask", null)
                        .WithMany()
                        .HasForeignKey("TriggeredByTaskId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VisualReference", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.DirectorDecision", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByDecisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("ImageAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Asset", null)
                        .WithMany()
                        .HasForeignKey("InheritsFromAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AlexDirectorConsole.V2.Database.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VoicePackage", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.VoiceTrainingJob", null)
                        .WithMany()
                        .HasForeignKey("VoiceTrainingJobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AlexDirectorConsole.V2.Database.Models.VoiceTrainingSample", b =>
                {
                    b.HasOne("AlexDirectorConsole.V2.Database.Models.VoiceTrainingJob", null)
                        .WithMany()
                        .HasForeignKey("VoiceTrainingJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
